version: "3.8"

services:
  # SvelteKit Frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trulycustom-web
    restart: unless-stopped

    environment:
      - VITE_POCKETBASE_URL
      - NODE_ENV=production
      - PB_ADMIN_PASSWORD
      - ORIGIN
    networks:
      - trulycustom-network

networks:
  trulycustom-network:
    driver: bridge
